# Generated by Django 4.1.4 on 2022-12-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
