# Generated by Django 4.1.4 on 2022-12-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_message_recipient_remove_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
