# Generated by Django 4.1.4 on 2022-12-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_message_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.EmailField(default='mgalazynn@gmail.com', max_length=254),
        ),
    ]
